# 02 — MATRICES (Linear Algebra for Machine Learning)

Authoritative reference notes for AI/ML.


## 1. What is a Matrix?
A **matrix** is a 2D arrangement of numbers in rows and columns.

Notation: A ∈ R^(m×n)

## 2. Types of Matrices
- Row Matrix
- Column Matrix
- Square Matrix
- Zero Matrix
- Identity Matrix
- Diagonal Matrix
- Symmetric Matrix
- Orthogonal Matrix

## 3. Matrix Operations
### Addition & Subtraction
Conditions: Same dimensions

### Scalar Multiplication
Multiply each element by a scalar

In [10]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A + B, A - B, 2 * A

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[2, 4],
        [6, 8]]))

## 4. Matrix Multiplication
Condition: (m×n)·(n×p)

In [11]:
A @ B

array([[19, 22],
       [43, 50]])

## 5. Transpose
Aᵀ flips rows into columns

In [12]:
A.T

array([[1, 3],
       [2, 4]])

## 6. Determinant
Indicates matrix invertibility

In [13]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

## 7. Inverse Matrix
A⁻¹ exists only if det(A) ≠ 0

In [14]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## 8. Rank of Matrix
Number of linearly independent rows/columns

In [15]:
np.linalg.matrix_rank(A)

np.int64(2)

## 9. Eigenvalues & Eigenvectors
Core concept for PCA and transformations

In [16]:
vals, vecs = np.linalg.eig(A)
vals, vecs

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

## 10. Matrix Norms
Measure magnitude

In [17]:
np.linalg.norm(A)

np.float64(5.477225575051661)

## 11. Matrices in Machine Learning
- Dataset representation
- Weight matrices
- Transformations
- Covariance matrices

## 12. Common Interview Notes
- Matrix multiplication is NOT commutative
- det(A)=0 ⇒ no inverse
- Eigenvectors define directions, eigenvalues define magnitude